name: CI Pipeline

on:
  push:
    branches: [ main, lincoln ]
  pull_request:
    branches: [ main ]

jobs:
  sast-bandit:
    name: Analyse SAST avec Bandit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer Bandit
        run: pip install bandit

      - name: Lancer Bandit en excluant les tests
        run: |
          bandit -r . -x unit_tests,integration_tests
