name: Analyse de sécurité avec Bandit

on:
  push:
    branches: [ main, lincoln ]
  pull_request:
    branches: [ main, lincoln ]

jobs:
  bandit-sast:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Installer Bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Lancer l'analyse de sécurité
      run: |
        echo "==== Analyse Bandit ===="
        bandit -r lincoln/ -x unit_tests/,integration_tests/ -ll
