name: Construction de l'image Docker

on:
  push:
    branches: [ main, lincoln ]
  pull_request:
    branches: [ main, lincoln ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Connexion à DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Construire et taguer l'image Docker
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/isen-python:dev-${{ github.sha }} .

    - name: Pousser l'image sur DockerHub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/isen-python:dev-${{ github.sha }}
