name: Dockerfile Lint avec Hadolint

on:
  push:
    branches: [ main, lincoln ]
  pull_request:
    branches: [ main, lincoln ]

jobs:
  dockerfile-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v2.2.0
        with:
          dockerfile: Dockerfile
