name: Analyse de code avec Pylint

on:
  push:
    branches: [ main, lincoln ]
  pull_request:
    branches: [ main, lincoln ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Analyser le code avec Pylint
      run: |
        echo "==== Analyse Pylint ===="
        pylint lincoln --fail-under=7 --disable=C,R0801 --ignore=tests_unitaires,integration_tests
