name: Analyse de code avec Pylint

on:
  push:
    branches: [ main, lincoln ]
  pull_request:
    branches: [ main, lincoln ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Préparer PYTHONPATH pour Pylint
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Analyser le code avec Pylint
        run: |
          echo "==== Analyse Pylint ===="
          pylint . --ignore=unit_tests,integration_tests

