name: Lint Python Code

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Install project requirements
        run: |
          pip install -r requirements.txt

      - name: Run pylint
        run: |
          pylint \
            --fail-under=7 \
            --disable=C,R0801,no-member,unused-import,redefined-builtin,arguments-differ \
            $(git ls-files '*.py')
