name: Trivy Scan de l'image Docker

on:
  push:
    branches: [ main, lincoln ]
  pull_request:
    branches: [ main, lincoln ]

jobs:
  trivy-scan:
    name: Run Trivy vulnerability scanner
    runs-on: ubuntu-latest
    continue-on-error: true  # ❗ Permet au pipeline de continuer même si des vulnérabilités sont détectées

    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.49.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.49.1_Linux-64bit.deb

      - name: Scan l'image Docker avec Trivy
        env:
          TRIVY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$TRIVY_PASSWORD" | docker login -u "$TRIVY_USERNAME" --password-stdin
          trivy image --severity HIGH,CRITICAL lincoln21/isen-python:distroless-dev-${{ github.sha }}
